# This is a basic workflow to help you get started with Actions

name: github-pages-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/tomsik68/karaoke.js-devcontainer
          cacheFrom: ghcr.io/tomsik68/karaoke.js-devcontainer
          push: always
      - name: Run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:    
          # [Optional] If you have a separate workflow like the one above
          # to pre-build your container image, you can reference it here
          # to speed up your application build workflows as well!
          cacheFrom: ghcr.io/tomsik68/karaoke.js-devcontainer
      
          push: never
          runCmd: pnpm build
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        with:
          # GitHub token
          token: # default is ${{ github.token }}
          artifact_name: public
